// Generated by CoffeeScript 1.8.0
(function() {
  var mongoDatabaseURI, mongoose;

  mongoose = require('mongoose');

  mongoDatabaseURI = 'mongodb://localhost:27017/chatsky';

  mongoose.connect(mongoDatabaseURI);

  mongoose.connection.on('connected', function() {
    return console.log('Mongoose default connection open to ' + mongoDatabaseURI);
  });

  mongoose.connection.on('error', function(err) {
    return console.log('Mongoose default connection error: ' + err);
  });

  mongoose.connection.on('disconnected', function() {
    return console.log('Mongoose default connection disconnected');
  });

  require("../model/User");

}).call(this);

//# sourceMappingURL=database.js.map
